apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: transmission
resources:
  - deployments/caddy.yaml
  - deployments/transmission.yaml
  - http-routes/default.yaml
  - http-routes/transmission.yaml
  - kustomization.flux.yaml
  - namespace.yaml
  - persistent-volume-claims/config.yaml
  - persistent-volume-claims/data.yaml
  - persistent-volumes/transmission-config.yaml
  - persistent-volumes/transmission-data.yaml
  - service-accounts/default.yaml
  - services/bittorrent.yaml
  - services/http-caddy.yaml
  - services/http-transmission.yaml
